### ISSUE TITLE
Redundant definitions of common variables

### ISSUE THREAD

**Issue by fscoto** [jedisct1/draft-aegis-aead#16]
The draft defined the input and output values `key`, `nonce`, `ad`, `msg`, `ct` and `tag` both at the top under "Conventions and Definitions" as well as for every function individually. This seems redundant and may invite misunderstandings: I'm looking at `Decrypt`, where `tag` has a different quality than it does as an output value; the output of `Encrypt` is a known-good tag, but `tag` as an input to `Decrypt` is a possibly-malicious input that affects the trustworthiness of the `ct` input. Perhaps I'm just overthinking it, too.

Is there any reason to keep both? I'm worried about the "Security Considerations" losing its primary reference point for the variables `key` and `nonce`, but I would imagine that sufficient context was given by the specification of the functions preceding this section.

The list at the top does specify the lengths, but the lengths are also part of the first paragraphs of each algorithm with the AEAD registry parameters.

If we do choose to have only one of these, I'd like to advocate for keeping only the definition at the top. People already familiar with implementing AEADs will only need to jump back for the lengths; people less familiar with common parlance in this space can reference functions they've written before.

**Comment by samuel-lucas6** [comment]
I see what you mean, but I didn't find it bothered me when I just proofread the document. You can make a case either way (convenient not having to scroll far if you forget vs repetition and implementors already being familiar with these types of parameters). 

I don't think it would be a problem for the 'Security Considerations' section, and I agree that it would probably be best leaving the top one.

**Comment by jedisct1** [comment]
My feeling is that having both actually increases clarity, and that making the document more concise wouldn't be a practical improvement.

The top definitions provides some context for the rest of the document.

But implementors are going to ignore this and jump straight to the function definitions.

It's convenient to have self-contained documentation for any function. Having to jump back is annoying and bug prone. It also doesn't match how the actual API will be documented.

**Comment by fscoto** [comment]
I guess we're keeping both then.
