### ISSUE TITLE
Context commitment

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/draft-aegis-aead#19]
A nice property of AEGIS is the fact that it is context committing.

Unlike AES-GCM and ChaChaPoly, for a given (key, nonce), distinct ADs will output different encryption keystreams, not just different MACs.

This offers some resistance against keys being reused in different contexts.

Is it something worth mentioning in the draft?

**Comment by samuel-lucas6** [comment]
I wasn't aware of that. I do think that's worth mentioning.
