### ISSUE TITLE
CFRG submission

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/draft-aegis-aead#20]
Thanks to your invaluable help, @fscoto and @samuel-lucas6, the draft looks really good for an initial version!

The structure and content seem to be quite usable to write independent implementations, and recent changes were mainly nitpicks.

Now is probably a good time to get external feedback. Do you think we should go ahead and submit it to the CFRG for review? Or is there anything you think we should address before doing so?

**Comment by fscoto** [comment]
I think it'd be advisable to do something about the “TODO acknowledge” part in the draft first. That just seems like we forgot something.

**Comment by samuel-lucas6** [comment]
Should I add myself as an editor or author now that I've contributed as well? Aside from that and #21, it looks good to go.

**Comment by fscoto** [comment]
> Should I add myself as an editor or author now that I've contributed as well?

Seems reasonable to me. If @jedisct1 gives you the ok, go ahead.

**Comment by jedisct1** [comment]
Go ahead! :)

**Comment by fscoto** [comment]
Just to make sure, you probably want to upload the as a standalone Internet-Draft first so that there's an actual authoritative draft in the sense the IETF uses the word before asking CFRG for feedback.

See also: https://github.com/martinthomson/i-d-template/blob/main/doc/FEATURES.md#what-this-project-can-do

**Comment by jedisct1** [comment]
@fscoto Done!

Any idea why the Intended RFC status is undefined, though?

Wasn't `category: info` supposed to set it to `informational`?

**Comment by fscoto** [comment]
It does show correctly in the XML. I wonder if this is an issue with . Maybe you have to submit the XML via the [IDST](https://datatracker.ietf.org/submit/) manualy at least once? Lots of other drafts seem to be suffering from the same issue.

**Comment by jedisct1** [comment]
Done!

And for some reason, the category is now showing up correctly.
