### ISSUE TITLE
Address Daniel's comments

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/draft-aegis-aead#25]
Daniel Bleichenbacher wrote:

> Possibly one source of confusion are subtle changes made to AEGIS by the authors.
> The description of the CAESAR submission as well as your IETF draft use 7 rounds in finalize of AEGIS256.
> The test vectors in the CAESAR submission and possibly a previous draft of AEGIS256 use 6 rounds.
>
> Another small difference I've noticed, which could lead to some confusion:
> The IACR version of AEGIS128L   (https://eprint.iacr.org/2013/695.pdf) computes the tag over S[0] .. S[7],
> while the CAESAR submission of AEGIS128L computes the tag over S[0] .. S[6].
> Your draft uses the CAESAR submission as expected.
>
> These differences when not being notices can lead to considerable confusion. Maybe it would be helpful
> if they were pointed out in your draft.

These differences may indeed be worth pointing out.

**Comment by samuel-lucas6** [comment]
I agree; that's a good point. Perhaps a sentence at the beginning of the relevant algorithm section or at the end of a subsection?

**Comment by jedisct1** [comment]
I'm not sure what the best place to mention this would be.

Instead of focusing on specific details, maybe we can warn in the intro about the existence of older, incompatible versions of the specification?

**Comment by samuel-lucas6** [comment]
> Instead of focusing on specific details, maybe we can warn in the intro about the existence of older, incompatible versions of the specification?

That makes more sense actually. Still not sure where unless maybe the first paragraph.
