### ISSUE TITLE
Adding invalid test vectors

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/draft-aegis-aead#36]
@soatok suggested we add test vectors that are invalid, as it can help implementers make sure that they properly check everything that has to be checked.

While adding such vectors wouldn't hurt, I'm still not convinced that they are necessary. That would be very useful for e.g. group elements accepting multiple representations, to make sure that implementations only accept canonical representations.

In the case of AEADs, these vectors might be useful for testing edge cases or common implementation mistakes. A suggested example is swapping the key and the nonce, which AEGIS facilitates since they share the same size.

However, as long as we have test vectors using different values for the nonce and the key, this case is already captured.

Did I miss something?

Implementations can forget to check the tag, so we can add a vector with an invalid tag, though.

**Comment by jedisct1** [comment]
@fscoto @samuel-lucas6 What are your thoughts on this?

**Comment by samuel-lucas6** [comment]
> However, as long as we have test vectors using different values for the nonce and the key, this case is already captured.
> 
> Did I miss something?

I don't think that covers this case. An example of what Soatok is suggesting would be Test Vector 4 but with the key as the nonce, the nonce as the key, and the message removed so it's just a test of decryption.

> Implementations can forget to check the tag, so we can add a vector with an invalid tag, though.

Is this referring to the same thing?

> A trivial "bit flipped in ciphertext and/or authentication tag" vector is also useful.

This suggestion also makes sense, but I don't know how many test vectors is too many. I think there should be at least one invalid tag check.

**Comment by fscoto** [comment]
Personally, I'm entirely on board for that since the unhappy path is, in fact, *a very important* path. The additional test vectors cause no harm, either; what would suffer from it, really?

I can see the following failure modes:

1. Tag is not checked.
2. Tag is only partially checked (e.g. typo `memcmp(mine, theirs, 15)`, which even visually looks similar).
3. Tag is checked against itself (e.g. copy-paste mistake `memcmp(tag, tag, 16)`). Compiler warnings should catch this, but not everyone reads warnings properly.
4. Ciphertext is released before the tag is checked. Though that can't be made into a test vector.

Unless I, too, missed something, that can be covered with two bit flips at the start and the end in one extra test vector.

**Comment by samuel-lucas6** [comment]
I'm confused as to whether we're all talking about the same thing. From what I understand, the Soatok test vectors could be:

1. Test Vector 3 or 4 but key = nonce, nonce = key, ad = same, msg = empty, ct = same, tag = same.

~~~
key  : 10000200000000000000000000000000
       00000000000000000000000000000000

nonce: 10010000000000000000000000000000
       00000000000000000000000000000000

ad   : 0001020304050607

msg  : 

ct   : f373079ed84b2709faee37358458

tag  : c60b9c2d33ceb058f96e6dd03c215652
~~~

2. Test Vector 3 or 4 but ct = bit flipped or ad = bit flipped and msg = empty. This could be split into two test vectors.

~~~
key  : 10010000000000000000000000000000
       00000000000000000000000000000000

nonce: 10000200000000000000000000000000
       00000000000000000000000000000000

ad   : 0001020304050607

msg  : 

ct   : f373079ed84b2709faee37358459

tag  : c60b9c2d33ceb058f96e6dd03c215652
~~~

Then are you suggesting one more with a bit flip in the tag (e.g. as done below) @fscoto? What are the two bit flips at the start? Shouldn't those be separate test vectors like above/what Soatok suggested?

~~~
key  : 10010000000000000000000000000000
       00000000000000000000000000000000

nonce: 10000200000000000000000000000000
       00000000000000000000000000000000

ad   : 0001020304050607

msg  : 

ct   : f373079ed84b2709faee37358458

tag  : c60b9c2d33ceb058f96e6dd03c215653
~~~

I'm happy to do the PR if it's just tweaking existing test vectors. The ChaCha20-Poly1305 RFC has quite a few test vectors, but I do think there should be a limit in place to not overwhelm people. However, these three seem reasonable.

**Comment by fscoto** [comment]
@samuel-lucas6, I meant one bit flip in the first octet of start and one at the last octet of the tag.
