### ISSUE TITLE
Emphasising that AEGIS is not nonce-misuse resistant

### ISSUE THREAD

**Issue by samuel-lucas6** [jedisct1/draft-aegis-aead#38]
> If verification fails, the decrypted message and wrong message authentication tag MUST NOT be given as output

1. Like this sentence, should we write something akin to 'the nonce MUST NOT be reused' in multiple sections rather than just the 'Security Considerations' to really hammer the point home?

> Moreover, AEGIS is context committing, meaning different associated data for a (key, nonce) pair results in a different keystream for encryption, not just a different authentication tag. This provides some resistance against key reuse when encrypting data in different contexts.

2. For this paragraph in the 'Introduction', should we also explicitly state that the nonce cannot be reused?

> Oftentimes, nonce space is another issue; randomly chosen nonces may be safe for only a very limited number of messages. Nonces may be safely chosen at random with no practical limit when using AEGIS-256; this applies irrespective of the length of individual or total messages.

3. We could state as a final sentence how this helps avoid nonce reuse, which is catastrophic for security.

Are there any other places where we could highlight how nonces must not be reused?

**Comment by samuel-lucas6** [comment]
Also, not to get too off topic, but regarding releasing the plaintext, I don't think there's much more we can do. It's stated three times, and I don't know where else we would mention it. The only thing I can think of would be moving the note to the 'Outputs' bullet points:

> Outputs:
> - either the decrypted message msg, or an error indicating that the authentication tag is invalid for the given inputs. If verification fails, the decrypted message and wrong message authentication tag MUST NOT be given as output.

Is it more likely to be read there or at the bottom of the section?

**Comment by jedisct1** [comment]
> Like this sentence, should we write something akin to 'the nonce MUST NOT be reused' in multiple sections rather than just the 'Security Considerations' to really hammer the point home?

Yes, that wouldn't hurt.

> For this paragraph in the 'Introduction', should we also explicitly state that the nonce cannot be reused?

I'd suggest we remove the entire paragraph instead.

> We could state as a final sentence how this helps avoid nonce reuse, which is catastrophic for security.

That would be a little bit redundant.

**Comment by jedisct1** [comment]
> Also, not to get too off topic, but regarding releasing the plaintext, I don't think there's much more we can do. 

I agree. We are stating it multiple times, and the function definitions makes it clear as well.

> Is it more likely to be read there or at the bottom of the section?

Having it here feels more contextual. People don't read fine prints at the end of sections :)

**Comment by samuel-lucas6** [comment]
> Having it here feels more contextual. People don't read fine prints at the end of sections :)

@jedisct1 To clarify, do you still think that sentence should be moved to the 'Outputs' section? I have a PR ready if so.

My alternative suggestion would be to have a bullet-pointed 'Security' section, perhaps at the beginning before 'Inputs' so it will get read. Even at the end of the section, I think making it a named section and having bullet points would help with readability and highlighting the importance.

> 4.1. Authenticated Encryption
> 
> Encrypt(msg, ad, key, nonce)
> 
> The Encrypt function encrypts a message and returns the ciphertext along with an authentication tag that verifies the authenticity of the message and associated data, if provided.
> 
> Security:
> - The nonce MUST NOT be reused under any circumstances; doing so allows an attacker to recover the internal state.
> - If verification fails, the decrypted message and wrong message authentication tag MUST NOT be given as output.
> - If the decryption process is implemented such that a buffer is supplied by the caller and said buffer is modified to contain partial decrypted data, the buffer MUST fully overwrite the supplied buffer with non-secret data, such as setting it to an all-zero value.
> - The comparison of the input `tag` with the `expected_tag` SHOULD be done in constant time.
> 
> Inputs:
> - msg: the message to be encrypted.
> - ad: the associated data to authenticate.
> - key: the encryption key.
> - nonce: the public nonce.

I could do a PR for that instead. Thoughts as well @fscoto?

**Comment by fscoto** [comment]
Personally? I like this bullet-pointed security sub-section idea. It's actually more readable and harder to miss. Unless @jedisct1 objects, that seems fine to me in principle.

Note that the sections about `Encrypt()` cannot possible talk about an input `tag`.

**Comment by samuel-lucas6** [comment]
> Note that the sections about Encrypt() cannot possible talk about an input tag.

Corrected that thanks. Did a weird hybrid of both encryption and decryption sections there.

**Comment by jedisct1** [comment]
Let's opt for the bullet-pointed sub-section, then! :)
