### ISSUE TITLE
More AEGIS analysis

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/draft-aegis-aead#46]
Including more papers on AEGIS may be useful to show that it's got some scrutiny.

- https://ietresearch.onlinelibrary.wiley.com/doi/full/10.1049/cje.2020.00.231
- https://eprint.iacr.org/2018/292.pdf
- https://academic.oup.com/comjnl/advance-article-abstract/doi/10.1093/comjnl/bxab059/6280579
- https://eprint.iacr.org/2021/187
- https://tosc.iacr.org/index.php/ToSC/article/view/8468

Some only cover the AEGIS128 variant. Do you think they are still worth including?

**Comment by jedisct1** [comment]
Bart suggests:

Andreeva, E., Bogdanov, A., Luykx, A., Mennink, B., Mouha, N., and Yasuda, K.,
"How to Securely Release Unverified Plaintext in Authenticated Encryption,"
Advances in Cryptology. ASIACRYPT 2014. Lecture Notes in Computer Science, vol 8873.
Springer, <https://doi.org/10.1007/978-3-662-45611-8_6>

Eichlseder, M., Nageler, M., and Primas, R. (2020), "Analyzing the
Linear Keystream Biases in AEGIS", IACR Transactions on Symmetric Cryptology,
2019(4), pp 348–368, <https://doi.org/10.13154/tosc.v2019.i4.348-368>

Liu, F., Isobe, T., Meier, W., and Sakamoto, K. (2021), "Weak Keys in Reduced
AEGIS and Tiaoxin", IACR Transactions on Symmetric Cryptology, 2021(2), pp 104–139, <https://doi.org/10.46586/tosc.v2021.i2.104-139>

Minaud, B., "Linear biases in AEGIS keystream", Selected Areas in
Cryptography. SAC 2014. Lecture Notes in Computer Science, vol 8781,
Springer, pp 290–305, <https://doi.org/10.1007/978-3-319-13051-4_18>

**Comment by jedisct1** [comment]
Looks like the same list, without SHI et al.'s paper.

**Comment by samuel-lucas6** [comment]
> How about removing only the first one from SHI et al. ?

That/Bart's suggestions sound good.
