### ISSUE TITLE
Neil Madden's Feedback

### ISSUE THREAD

**Issue by samuel-lucas6** [jedisct1/draft-aegis-aead#49]
As said in #48, here's a summary:

1. Add an explicit reference to the CAESAR competition (is there some kind of final report?).
2. ~Mention that AEGIS was selected for the high-performance scenario. AEGIS-128L is somewhat at odds with the competition outcome.~ (DONE)
3. Perhaps an alternative term like “chunk” could be used for input blocks to distinguish them from AES blocks?
4. ~I would perhaps be inclined to simplify things even further and only document the AEGIS-128L variant, which seems like the best pick of the three for the intended use cases.~ (256-bit variant as an alternative to AES-GCM)
5. ~The discussion of partitioning oracle (PO) attacks could be moved from the introduction to a later section (perhaps section 6), with perhaps just a short note in the intro that AEGIS is key-committing and therefore resists partitioning oracle attacks.~ (Simplified slightly but summary useful)
6. ~Add 'using a suitable password-based key derivation function' to the partitioning oracle attacks paragraph to avoid implying that a password can be used directly.~ (This was removed)
7. ~Add a reference for the partitioning oracle attacks 'padding block'/zero check.~ (Removed)
8. ~What is the implication of leaking the state? In GCM nonce-reuse allows (among other things) recovery of the MAC sub-key and subsequent forgeries.~
9. Does nonce reuse have no impact on integrity, only on confidentiality?
10. ~The “for a given key” caveat is missing from the note in section 3.1 and should probably be added.~ (DONE)
11. ~The requirement to compare the MAC tag in constant time is only a SHOULD. I can’t see any good reason not to make this a MUST given how simple it is to implement?~ (DONE)
12. ~What's the purpose of section 5? Would the JOSE implementation be non-compliant?~ (Guarantees interoperability)
13. ~Define 'context-committing'.~ (This was removed)

**Comment by samuel-lucas6** [comment]
I would also add that a reference and definition for compactly-committing would be wise. There seem to be overlapping definitions for key-committing, message-committing, compactly-committing, committing AEAD, and random key robustness (RKR). It's all unnecessarily confusing.

**Comment by jedisct1** [comment]
Describing the properties rather than using jargon would probably reduce confusion.
- Multiple ciphertexts can produce the same tag (inevitable with a 128-bit tag)  
- Finding multiple keys for which a (ciphertext, tag) pair is valid is impractical.

**Comment by fscoto** [comment]
Got one note:

> What's the purpose of section 5? Would the JOSE implementation be non-compliant?

From where I stand, the purpose of section 5 is to make sure that there's *a* canonical ordering if any spec (even outside the IETF) just says to encrypt with AEGIS. For JOSE, the tags are distinct (cf. RFC 7516 § 5.1: `BASE64URL(JWE Ciphertext) || '.' || BASE64URL(JWE Authentication Tag)`).

Incidentally, RFC 8439 § 2.8 (ChaPoly) states that “[t]he output from the AEAD is the concatenation of: o  A ciphertext of the same length as the plaintext. o  A 128-bit tag, which is the output of the Poly1305 function.”), with the difference being there's no MUST there and it just being required by spec ambiguously.

**Comment by jedisct1** [comment]
Leaking the state doesn't leak the key, doesn't leak previous states either.

**Comment by fscoto** [comment]
Updates from meeting 2022-06-02:

> 1. Add an explicit reference to the CAESAR competition (is there some kind of final report?).

No final report was produced that anybody knew of. Nothing to cite.

> 3. Perhaps an alternative term like “chunk” could be used for input blocks to distinguish them from AES blocks?

Still open AFAICT. I disagree since symmetry of input and output size is in the nature of a block cipher. Using the term block for both emphasizes identical length. Plus in my experience "chunk" tends to be used a layer up for a protocol-level ciphertext.

> 8. What is the implication of leaking the state? In GCM nonce-reuse allows (among other things) recovery of the MAC sub-key and subsequent forgeries.
>
> 9. Does nonce reuse have no impact on integrity, only on confidentiality?

We actually have a paragraph on 8 in the intro already:

> Finally, unlike most other AES-based AEAD constructions, such as Rocca and Tiaoxin, leaking the state does not leak the key.

This is part of the sales pitch (better resistance to catastrophic failure), so I vote to keep things as-is.

As for 9, we agreed on 2022-06-04 not toinclude too many cryptographic details since the document is aimed at implementers primarily.

From where I stand, this issue can be closed with everything being either addressed or wontfix.

**Comment by samuel-lucas6** [comment]
> From where I stand, this issue can be closed with everything being either addressed or wontfix.

That's fair. I wasn't sure whether we could cite the CAESAR competition webpage, but it seems not. I'll go ahead and close it based on the meeting response.
