### ISSUE TITLE
Adam Langley's Feedback

### ISSUE THREAD

**Issue by samuel-lucas6** [jedisct1/draft-aegis-aead#52]
I've got some feedback from Adam Langley to share:

> I've not tried to implement it from the specification, which is really the definitive test, but it certainly appears that one could. So, overall, looks good!
> 
> A couple of things came to mind:
> 
> I'm not sure that the test vectors are sufficient to exercise a real implementation. For 128L, I think there are none that contain more than one block of message input? And none that contain more than one block of AD input?
> 
> Second, there are surely more bounds than expressed in the draft. (I didn't look into the cited papers so quite possibly they are included there!) E.g. given a maximum plaintext of 2^61 bytes, it doesn't take that many messages before the birthday bound of AES starts to bite, no? If available, something like https://www.ietf.org/id/draft-irtf-cfrg-aead-limits-04.html#name-aead_aes_128_gcm-and-aead_a for AGEIS might be interesting.
> 
> I don't think either issue is blocking: the draft as-is feels like it could be an RFC.

Thank you again @agl!

I also reached out to the partitioning oracle attack authors, and Julia kindly said they'd have a look.

**Comment by jedisct1** [comment]
The test vectors have been added.

Thanks for that useful feedback!
