### ISSUE TITLE
add bit lengths to the algorithm parameters sections

### ISSUE THREAD

**Issue by ericlagergren** [jedisct1/draft-aegis-aead#54]
A quite minor nitpick: the RFC describes the length of all strings using bits, except in the algorithm parameters section where it uses octets. I was comparing the paper and the RFC and was briefly confused by the unit switch ("where does 2^61 come from?") since the paper (and the rest of the RFC) use bits, not octets.

Of course, once I realized my mistake it was obvious. But perhaps those sections could list the bit lengths in parentheses? E.g.,

    P_MAX (maximum length of the plaintext) is 2^61 octets (2^64 bits).

**Comment by jedisct1** [comment]
Great suggestion, thank you Eric!
