### ISSUE TITLE
Mention Project Wycheproof test vectors?

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/draft-aegis-aead#57]
People should be aware that Project Wycheproof includes extensive test vectors for AEGIS.

We can add a link to the list of implementations, but is it something we could add to the document itself?
URLs are probably not acceptable in a RFC, so I'm not sure how it could be done.

**Comment by fscoto** [comment]
Name dropping it without a link is marginally useful now, but if it ever gets removed/moved/forked/..., it'll be tough to find.

RFC 7322 (RFC Style Guide) § 4.8.6.1 is the sole mention of when URLs/URIs are permitted; it is located in the section for *references* and states:

>   The use of URIs in references is acceptable, as long as the URI is
>   the most stable (i.e., unlikely to change and expected to be
>   continuously available) and direct reference possible.  The URI will
>   be verified as valid during the RFC editorial process.
>
>   If a dated URI (one that includes a timestamp for the page) is
>   available for a referenced web page, its use is required.
>
>   Note that URIs may not be the sole information provided for a
>   reference entry.

Considering Wycheproof is not a reference, this is going to be questionable. One might be able to skirt this rule by taking one or more test vectors from there and adding a note that more, extensive vectors may be found in there, thereby "citing" the reference. It's also going to be hard to tell if it should be a normative reference.

I couldn't find any other RFC or I-D mentioning Wycheproof.

Personally, I therefore lean towards not mentioning it.

**Comment by samuel-lucas6** [comment]
> Name dropping it without a link is marginally useful now, but if it ever gets removed/moved/forked/..., it'll be tough to find.

It seems very unlikely that it'll go away completely though, so a name drop is probably acceptable.

**Comment by jedisct1** [comment]
During HACS in Tokyo, Google announced that Project Wycheproof is going to eventually accept contributions, and that the tools they use to build the test vectors will be open sourced.

But it's going to take time, especially with the recent changes at Google.

In the meantime, I agree that we should just close this issue.
