### ISSUE TITLE
Add IANA assigned numbers for use in TLS

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/draft-aegis-aead#66]
IANA just assigned identifiers to use AEGIS in TLS:

https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml

```text
0x13,0x06 TLS_AEGIS_256_SHA384
0x13,0x07 TLS_AEGIS_128L_SHA256
```

We should update the `IANA Considerations` section accordingly (not removing the note about the `AEAD` registry, which is a different one).

**Comment by fscoto** [comment]
Cool! Did you request the assignment or was it a third party assignment that you were made aware of?

The draft is listed as specification. People are going to start depending on it. I guess we'll see if anything is mis-specified soon enough as people start implementing.

I'll try to hammer out a draft tomorrow unless one of you beats me to it.

**Comment by jedisct1** [comment]
The request was made on the behalf of Fastly, then experts reviewed the application.

I have a BoringSSL branch supporting it, which, along with the now assigned identifiers, will make it easy to add AEGIS support to existing code using TLS.

**Comment by jedisct1** [comment]
Go ahead for the draft. I'll be probably AFK over the weekend.

We need to send updates to the CFRG list about the draft, btw.

It may be good to define AEGIS in term of draft-bozhko-cfrg-aead-properties which is also being discussed right now.

But the algorithm specification is unlikely to change, and all the feedback we got has been addressed. So it's probably safe for people to start relying on the current draft.

**Comment by fscoto** [comment]
> It may be good to define AEGIS in term of draft-bozhko-cfrg-aead-properties which is also being discussed right now.

As far as I can tell, there's not much to define "in terms of". Said draft defines required properties of an AEAD. AEGIS fails because it does not provide any kind of nonce misuse resistance (§ 3.1.8). It may still be useful to note which ones are not provided and why, but should probably be tracked in a separate issue.
