### ISSUE TITLE
Lengths of parameters

### ISSUE THREAD

**Issue by fscoto** [jedisct1/draft-aegis-aead#7]
The lengths of parameters are inconsistently used. For example, `tag` is noted to be "the 128-bit authentication tag" several times, but the lengths of `k` and `iv` aren't repeated in every function description.

Should this be consistently added to all descriptions or consistently removed since the lengths are given in the beginning of the draft?

**Comment by jedisct1** [comment]
Having this added to all descriptions may feel very redundant, so maybe would should just remove it everywhere
