### ISSUE TITLE
Mention that the key can be erased after initialization

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/draft-aegis-aead#95]
This is a natural property of a scheme based on a sponge, but it may still worth mentioning this.

The key can be erased right after initialization. In fact, even after the first update round. 

Ephemeral shared keys can thus stay in memory for a minimal amount of time, compared to ChaChaPoly or other AES-based constructions where the key, or the key schedule has to remain in memory until the end of the message. With AEGIS, it can be erased even before anything is encrypted.

That has practical applications. In particular when encrypting sensitive customer data, with the ephemeral key being only stored as encrypted with the customer's public key (or encapsulated with a KEM). The customer can rest assured that the encryption key only stays in the server's memory for a minimal amount of time, regardless of the message size.

**Comment by samuel-lucas6** [comment]
That's an interesting point I haven't heard before. Do you think that should go in the Introduction or Security Considerations (or both)?

**Comment by jedisct1** [comment]
Since the intro already mentions key commitment and the fact that the state is non invertible, maybe in the intro?

The "security considerations" section is more about how to use the constructions safely.

On the other hand, where should we mention that the key is only required for the first `Update()` call?

**Comment by samuel-lucas6** [comment]
> Since the intro already mentions key commitment and the fact that the state is non invertible, maybe in the intro?

Yeah, by the leaking the state part sounds good. It's an advantage so this makes sense.

> The "security considerations" section is more about how to use the constructions safely.
>
> On the other hand, where should we mention that the key is only required for the first Update() call?

I hear you. I was thinking about the tag verification and timing attack parts. Three options:

1. The Init Function after the description. Inconsistent with the other sections though.
2. Security subsection of Authenticated Encryption/Decryption. Leads to a lot of repetition.
3. Security Considerations, which avoids writing the same thing in multiple places but is easier to miss.

Any others?

**Comment by jedisct1** [comment]
Maybe in the intro, we can say that the key is only necessary for the first initialization step, and can thus be quickly erased from memory, even before any data has been encrypted or decrypted (no references to any particular init function, nor to the `Update()` function that hasn't been defined yet).

And then be more explicit the security consideration.

**Comment by samuel-lucas6** [comment]
> Maybe in the intro, we can say that the key is only necessary for the first initialization step, and can thus be quickly erased from memory, even before any data has been encrypted or decrypted (no references to any particular init function, nor to the Update() function that hasn't been defined yet).

That's good.

> And then be more explicit in the security considerations.

That's fine by me. It works there.
